"""Authentication service backed by repository persistence."""

from __future__ import annotations

from dataclasses import dataclass
import secrets

import bcrypt

from src.core.exceptions import AuthenticationError, ConflictError
from src.core.settings import Settings
from src.core.utils import new_document_id, utc_now
from src.repositories.base import UserRepository
from src.schemas.documents import UserAccountDocument


@dataclass
class AuthResult:
    """Structured auth response generated by AuthService."""

    user: UserAccountDocument
    access_token: str
    token_type: str
    message: str


class AuthService:
    """Handle signup and login using persisted user accounts."""

    def __init__(self, users: UserRepository, settings: Settings):
        self.users = users
        self.settings = settings

    async def signup(
        self,
        full_name: str,
        email: str,
        password: str,
        role: str,
    ) -> AuthResult:
        normalized_email = self._normalize_email(email)
        existing = await self.users.get_by_email(normalized_email)
        if existing is not None:
            raise ConflictError("An account with this email already exists.")

        hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
        account = UserAccountDocument(
            id=new_document_id("user"),
            full_name=full_name.strip(),
            email=normalized_email,
            role=role,
            password_salt="",  # salt is embedded inside the bcrypt hash
            password_hash=hashed.decode(),
            created_at=utc_now(),
            last_login_at=None,
        )
        stored = await self.users.create(account)
        return AuthResult(
            user=stored,
            access_token=self._issue_access_token(),
            token_type="bearer",
            message="Account created successfully.",
        )

    async def login(self, email: str, password: str) -> AuthResult:
        normalized_email = self._normalize_email(email)
        user = await self.users.get_by_email(normalized_email)
        if user is None:
            raise AuthenticationError("Invalid email or password.")

        if not bcrypt.checkpw(password.encode(), user.password_hash.encode()):
            raise AuthenticationError("Invalid email or password.")

        updated = await self.users.update_last_login(user.id, utc_now())
        return AuthResult(
            user=updated,
            access_token=self._issue_access_token(),
            token_type="bearer",
            message="Login successful.",
        )

    @staticmethod
    def _normalize_email(email: str) -> str:
        return email.strip().lower()

    @staticmethod
    def _issue_access_token() -> str:
        return secrets.token_urlsafe(32)
